### PR TITLE
added a datamanager callback

### PR DESCRIPTION
**Pull request by thunder-hammer**
I need to add tests before we should merge this.

### CODE REVIEW

**Comment by thunder-hammer** [comment]
Although it does pass existing tests so I suppose it could be merged.

**Comment by andrewmkeller** [comment]
I am confused. What existing tests does it not pass? I would like to have it pass existing tests and have close to 100% test coverage before merging...

**Comment by thunder-hammer** [comment]
Sorry about that. It passes all tests that exist but has none of its own.

**Comment by thunder-hammer** [comment]
This passes all tests. as of the writing of this the build check is not passed. When it is done I think it should be good to go.

**Pull request merged**
