### PR TITLE
SpyDrNet Extensions [ PR 1/3 ] - Added extension discovery and  logger

### PR DESCRIPTION
**Pull request by ganeshgore**
Hello all,
For merging the spydrnet extension-related changes I planned to make three different PRs in the following order for ease of review. I am expecting this order will not break any CI runs.

1. Init file changes + logger
2. Change imports in all files 
3. changing spydrnet.ir.__init__

### CODE REVIEW

**Comment by ganeshgore** [comment]
@jacobdbrown4  Are we going to continue supporting Python 3.5?

**Comment by jacobdbrown4** [comment]
No, with this next release we will be dropping support for 3.5. You can go ahead and change that in this pull request.

**Comment by ganeshgore** [comment]
Ok, let me try to fix it by keeping 3.5 for now. this one should be simple

**Comment by jacobdbrown4** [comment]
This looks good. Can you briefly explain how the logger works and what it is meant to do?

**Comment by ganeshgore** [comment]
The logger is essentially a python logging module, it allows you to set the verbosity of your print messages.
You can set INFO, DEBUG, WARNING, CRITICAL etc. 
https://docs.python.org/3/library/logging.html 

This is how you can invoke it 
https://github.com/ganeshgore/spydrnet-physical/blob/fb9dcc6777a9b55b768932e3d0f3474047980223/examples/OpenFPGA/splitting_connection_box.py#L41

and this is how you can use  
https://github.com/ganeshgore/spydrnet-physical/blob/fb9dcc6777a9b55b768932e3d0f3474047980223/examples/OpenFPGA/splitting_connection_box.py#L68

It prints much better messages like below, which tell you which line is printing that message and what is the severity of it is.
```
WARNING definition.py:728 (MainThread) - No driver for mux2_size8_0_sram[0]
WARNING definition.py:730 (MainThread) - S Direction.IN MUX2_X1
WARNING definition.py:728 (MainThread) - No driver for mux2_size8_0_sram[1]
WARNING definition.py:730 (MainThread) - S Direction.IN MUX2_X1
WARNING definition.py:730 (MainThread) - S Direction.IN MUX2_X1
WARNING definition.py:730 (MainThread) - S Direction.IN MUX2_X1
```

**Comment by ganeshgore** [comment]
In this particular setup, the logger will print messages on the console as well as in the log file  (`_spydernet.log`). 
and you can adjust the verbosity of each stream explicitly. This generally helps in debugging.

**Pull request merged**
