### PR TITLE
SpyDrNet Extensions [ PR 3/3 ] - Updated spydrnet.ir.__init__ file 

### PR DESCRIPTION
**Pull request by ganeshgore**
These are final changes that extend the classes.

### CODE REVIEW

**Comment by ganeshgore** [comment]
Technically there is only one file changed from PR 2/3 `spydrnet.it.__init__.py`

**Comment by ganeshgore** [comment]
The green CI status for this PR ensures that these extension-related changes do not affect the spydrnet base functionally. However, to verify if the extension load properly or not we shud create one dummy extension in the separate repo or directory and load it in during CI and verify. let me know your thoughts

**Comment by jacobdbrown4** [comment]
> The green CI status for this PR ensures that these extension-related changes do not affect the spydrnet base functionally. However, to verify if the extension load properly or not we shud create one dummy extension in the separate repo or directory and load it in during CI and verify. let me know your thoughts

I think that's a good idea.

**Comment by ganeshgore** [comment]
If these changes are good we should go ahead and merge them, 
I will make the next PR with a separate directory (`spydrnet-extension`) with a dummy extension module.

**Comment by jacobdbrown4** [comment]
I would like Dr. Wirthlin to have a chance to take a look at everything and then we'll go ahead and merge. Hopefully tomorrow we can merge them.

**Comment by ganeshgore** [comment]
Sounds good, I will try to push example extension as well tonight

**Pull request merged**
